# DMD for SET Data

Date: 07/08/2019

## Creating Dataset for DMD

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
## Import data set

df = pd.read_csv('SET data archive 3416 cases recd thru end of 03 2019_cleaned_general.csv')
df.head()

,Unnamed: 0,UniqueID,no_intake_question,no_retest1_question,no_retest2_question,SET_program_num,ETO_PROGRAM,SET_admin_num,baseline_type,enroll_SET_type_num,...,Completed_by_CIW,CIW_CLIENT_ID,CIW_INTERVIEW_DATE,CIW_COMPLETED_DATE,CIW1,CIW2,CIW3,CIW4,CIW5,CIW6_COMMENTS
0,3,49866,,,,1,1,1,,,...,999,,,,1.0,4.0,4.0,1.0,3.0,Client's son is helping him to change little b...
1,4,49868,,,,1,1,1,,,...,999,,,,2.0,3.0,4.0,1.0,3.0,Slow progress
2,5,49870,,,,1,1,1,,,...,999,,,,2.0,3.0,3.0,1.0,3.0,She goes there a lot ?home? She is trying to c...
3,8,47002,,,,1,1,1,,,...,999,Southwest 2-23-230-1,9/13/2018,9/13/2018,2.0,3.0,1.0,4.0,0.0,Client has been attending program and is stayi...
4,13,41570,,,,2,2,1,,1,...,999,SSSEARE-0-100-1,,,NaN,NaN,NaN,NaN,NaN,no page 17 completed

In [6]:
df['S10'].value_counts()

0.0    1077
1.0     681
2.0     492
3.0     289
4.0     120
5.0      49
6.0      23
7.0      19
Name: S10, dtype: int64

In [3]:
col_kept = ['UniqueID']
col_kept.extend(df.loc[:,'intake':'retest'].columns.tolist())
col_kept.extend(df.loc[:,'GRYD_Zone_num':'INTERVIEW_DATE_FB'].columns.tolist())
col_kept.extend(df.loc[:,'ENROLLMENT_DATE_1':'SEX_1'].columns.tolist())

In [10]:
# S section
que = df.loc[:,'S1':'S3'].columns.tolist()
que.extend(df.loc[:,'S4x':'S6ax'].columns.tolist())
que.extend(df.loc[:,'S9':'S10'].columns.tolist())
que.extend(df.loc[:,'S10x':'S11a'].columns.tolist())
que.extend(df.loc[:,'S11b':'S16'].columns.tolist())

# ME,P,C section
que.extend(df.loc[:,'ME17':'P26'].columns.tolist())
que.extend(['C1a','C2a','C3a','C4a','C5a'])

# FS section
que.extend(df.loc[:,'FS89_foster_now':'FS89_alone_past'].columns.tolist())

# F section
f_que.extend(df.loc[:,'F1':'F3'].columns.tolist())
f_que.extend(df.loc[:,'F4':'FS98'].columns.tolist())
f_que.extend(df.loc[:,'FS100':'F17x'].columns.tolist())
f_que.extend(df.loc[:,'F18':'F31b'].columns.tolist())
que.extend(f_que)

# G section
g_que = df.loc[:,'G2':'G3a'].columns.tolist()
g_que = df.loc[:,'EG1':'G9'].columns.tolist()
g_que.extend(df.loc[:,'G10x':'G23x'].columns.tolist())
g_que.extend(df.loc[:,'G24':'G37'].columns.tolist())
que.extend(g_que)

# X section
que.extend(df.loc[:,'X18':'X22'].columns.tolist())

# O section
que.extend(['A1','A2','A3'])
o_que = df.loc[:,'O4':'O9'].columns.tolist()
o_que.extend(df.loc[:,'O10':'O15'].columns.tolist())
o_que.extend(df.loc[:,'O16':'O24'].columns.tolist())
que.extend(o_que)

# X section
que.extend(df.loc[:,'X10':'X17'].columns.tolist())

In [11]:
print(que)

['S1', 'S2', 'S3', 'S4x', 'S5x', 'S7x', 'S6ax', 'S9', 'S10', 'S10x', 'S10z', 'S11a', 'S11b', 'S12', 'S13', 'S14', 'S16', 'ME17', 'ME18', 'ME19', 'ME20a', 'ME20b', 'ME20x', 'ME22_ER', 'P22', 'P23', 'P24', 'P25', 'P26', 'C1a', 'C2a', 'C3a', 'C4a', 'C5a', 'FS89_foster_now', 'FS89_foster_past', 'FS89_group_now', 'FS89_group_past', 'FS89_adopted_now', 'FS89_adopted_past', 'FS89_parents_now', 'FS89_parents_past', 'FS89_relatives_now', 'FS89_relatives_past', 'FS89_spouse_now', 'FS89_spouse_past', 'FS89_boygirlfriend_now', 'FS89_boygirlfriend_past', 'FS89_alone_now', 'FS89_alone_past', 'FS90_younger', 'FS90_teenagers', 'FS90_20_29_adults', 'FS90_30_49_adults', 'FS90_older_adults', 'FS90_younger', 'FS90_teenagers', 'FS90_20_29_adults', 'FS90_30_49_adults', 'FS90_older_adults', 'F4', 'F5', 'FS91', 'FS92', 'FS93', 'FS94', 'FS95', 'FS96', 'FS97', 'FS98', 'FS100', 'FS101', 'FS102', 'FS103', 'FS104', 'FS105', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16a', 'F16bx', 'F17x', 'F18', 'F19', 'F20', 'F21', 'F22x', 'F23x', 'F24x', 'F25x', 'F26', 'F27', 'F28x', 'F29', 'F31x', 'F31b', 'F1', 'F2', 'F3', 'F4', 'F5', 'FS91', 'FS92', 'FS93', 'FS94', 'FS95', 'FS96', 'FS97', 'FS98', 'FS100', 'FS101', 'FS102', 'FS103', 'FS104', 'FS105', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16a', 'F16bx', 'F17x', 'F18', 'F19', 'F20', 'F21', 'F22x', 'F23x', 'F24x', 'F25x', 'F26', 'F27', 'F28x', 'F29', 'F31x', 'F31b', 'F1', 'F2', 'F3', 'F4', 'F5', 'FS91', 'FS92', 'FS93', 'FS94', 'FS95', 'FS96', 'FS97', 'FS98', 'FS100', 'FS101', 'FS102', 'FS103', 'FS104', 'FS105', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16a', 'F16bx', 'F17x', 'F18', 'F19', 'F20', 'F21', 'F22x', 'F23x', 'F24x', 'F25x', 'F26', 'F27', 'F28x', 'F29', 'F31x', 'F31b', 'EG1', 'EG2_most', 'EG2_youngest', 'EG2_oldest', 'EG3', 'EG4x', 'G5', 'G5_num', 'G6', 'G7', 'G8', 'G9', 'G10x', 'G11', 'G12x', 'G13', 'G14x', 'G15', 'G16', 'G17', 'G18', 'G19', 'G20', 'G21', 'G22a', 'G22bx', 'G23x', 'G24', 'G25', 'G26', 'G27', 'G28x', 'G29x', 'G30x', 'G31x', 'G32', 'G33', 'G34x', 'G35', 'G36x', 'G36b', 'G37', 'X18', 'X19', 'X20', 'X21', 'X22', 'A1', 'A2', 'A3', 'O4', 'O5', 'O6', 'O7x', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16', 'O17', 'O18', 'O19a', 'O19b', 'O20x', 'O21', 'O22', 'O23', 'O24', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17']